title: Ullallulloo
author:
  name: Ullallulloo
  email: ullallulloo@gmail.com
  site: https://ullallulloo.com
url: https://ullallulloo.com
themeColor: "#870087"

googleFonts:
  - Press+Start+2P

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "game_recommendations"
    values:
      layout: "game-recommendation"
  -
    scope:
      path: ""
      type: "game_tips"
    values:
      layout: "game-tip"

collections:
  pages:
    output: true
    permalink: /:name
  game_recommendations:
    output: true
    permalink: /game-recommendations/:name
  game_tips:
    output: true
    permalink: /game-tips/:name

permalink: /:name

sass:
  style: compressed

plugins:
  - jekyll-sitemap
